USE DATABASE LEARNCO;

USE SCHEMA GOLD_ANALYTICS;

CREATE OR REPLACE MASKING POLICY mask_pii AS (val STRING) 
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN val
    ELSE '****'
END;

ALTER TABLE STUDENTS 
MODIFY COLUMN first_name SET MASKING POLICY mask_pii;

ALTER TABLE STUDENTS 
MODIFY COLUMN last_name SET MASKING POLICY mask_pii;


CREATE OR REPLACE MASKING POLICY mask_email AS (val STRING) 
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN val
    ELSE CONCAT('****@', SPLIT_PART(val, '@', 2))
END;


ALTER TABLE STUDENTS 
MODIFY COLUMN email SET MASKING POLICY mask_email;



-- ALTER TABLE STUDENTS 
-- MODIFY COLUMN email UNSET MASKING POLICY;

-- ALTER TABLE STUDENTS 
-- MODIFY COLUMN first_name UNSET MASKING POLICY;

-- ALTER TABLE STUDENTS 
-- MODIFY COLUMN last_name UNSET MASKING POLICY;

SELECT CURRENT_ROLE();
SELECT * FROM STUDENTS limit 10;

SHOW MASKING POLICIES;
-- DROP MASKING POLICY mask_email;
-- DROP MASKING POLICY mask_pii;

USE ROLE ACCOUNTADMIN;