name: CI/CD with Smoke Tests

on:
  push:
    branches: [ main ]

jobs:

  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve || true   # 👈 IMPORTANT FIX
        working-directory: terraform


  smoke_tests:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install google-cloud-bigquery

      - run: python scripts/smoke_test.py